[book]
src = "src"
title = ""

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://dapp-devs.com/ssh://git@git.2222/lumos-labs/xassets/contracts/synths-contracts"

[output.html.fold]
enable = true
